# Generated by Django 5.0.2 on 2024-06-23 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0004_auto_20240516_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_code', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('billiing', models.CharField(max_length=255)),
                ('billiing_method', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee_mail', models.CharField(max_length=255)),
                ('task_details', models.CharField(max_length=255)),
                ('task_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('billable', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.customer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.payroll_employee')),
            ],
        ),
    ]
